SyncCRM/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



app_name="users"
urlpatterns = [
    path('', include("leads.urls")),
    path('', include("users.urls")),
    path('login/', auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name="users/logout.html"), name="logout"),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name="users/password_reset.html"), name="password_resest"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"), name="password_resest_done"),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html"), name="password_resest-confirm"),
    path('admin/', admin.site.urls),

    # REST API URLS
    path('api/', include("leads.api.urls") ),
    path('api/user/', include("users.api.urls") ),

] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leads/api/urls.py
from leads.api.views import leadList, userLeadList, userList, updateLeadList,createLead
from django.urls import path

urlpatterns = [
    path("", leadList, name="api_leads"),
    path("<int:pk>/create/", createLead, name="api_create_lead"),
    path("users/", userList, name="api_users"),
    path("<int:id>", userLeadList, name="api_leads_user"),
    path("<int:id>/update/", updateLeadList, name="api_leads_update"),
]

leads/urls.py
from django.contrib import admin
from django.urls import path, reverse
from . import views
from .models import Lead

app_name = 'leads'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('create/', views.LeadCreate.as_view(), name="create"),
    path('myleads/', views.user_lead, name="mylead"),
    path('<int:pk>/update/', views.LeadUpdate.as_view(), name="update"),
    path('<int:pk>/delete/', views.LeadDelete.as_view(), name="delete"),
]

users/urls.py
from django.contrib import admin
from django.urls import path, reverse
from . import views as user_views

app_name = 'users'
urlpatterns = [
    path('signup/', user_views.register, name="register"),
    path('profile/', user_views.profile, name="profile"),
]

leads/models.py
from django.db import models
from django.contrib.auth.models import User

class Lead(models.Model):
    lead_title = models.CharField(max_length=100)
    lead_text = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, default='', on_delete=models.CASCADE)

    def __str__(self):
        return self.lead_title

leads/api/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework.views import APIView
from leads.api.serializers import LeadSerializer, UserSerializer
from leads.models import Lead
from django.contrib.auth.models import User



@api_view(['GET',])
def leadList(request):
    # return Response({"message": "Hello, World!"})
    
    serializer = LeadSerializer(Lead.objects.all(), many=True)
    return Response(serializer.data, status=status.HTTP_200_OK)

@api_view(['GET',])
def userList(request):
    # return Response({"message": "Hello, World!"})
    
    serializer = UserSerializer(User.objects.all(), many=True)
    return Response(serializer.data, status=status.HTTP_200_OK)

@api_view(['GET',])
def userLeadList(request, id):
    # return Response({"message": "Hello, World!"})
    
    serializer = LeadSerializer(Lead.objects.filter(user_id=id), many=True)
    return Response(serializer.data, status=status.HTTP_200_OK)


@api_view(['POST',])
def createLead(request, pk):
    # return Response({"message": "Hello, World!"})
    user = User.objects.get(pk=pk)
    lead = Lead(user=user)

    if request.method == "POST":
        serializer = LeadSerializer(lead, data=request.data)
        data={}
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    

@api_view(['PUT',])
def updateLeadList(request, id):
    # return Response({"message": "Hello, World!"})
    
    serializer = LeadSerializer(Lead.objects.get(id=id), data=request.data)
    data = {}
    if serializer.is_valid():
        serializer.save()
        data["success"] = "Update Successfull"
        return Response(data=data)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    


# class ListLeads(APIView):
#     http_method_names = ['get', 'head']
#     def get(self, request, format=None):
#         # import pdb; pdb.set_trace()
#         serializer = LeadSerializer(Lead.objects.all(), many=True)
#         return Response(serializer.data, status=status.HTTP_200_OK)

leads/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Lead

class IndexView(generic.ListView):
    template_name = "leads/index.html"
    # context_object_name = "leads"
    def get_queryset(self):
        return Lead.objects.order_by("-created_at")

class LeadCreate(CreateView):
    model = Lead
    fields = ['lead_title','lead_text']
    success_url = reverse_lazy('leads:index')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(LeadCreate, self).form_valid(form)

class LeadUpdate(UpdateView):
    model = Lead
    fields = ['lead_title','lead_text']
    success_url = reverse_lazy('leads:index')
    
class LeadDelete(DeleteView):
    model = Lead
    success_url = reverse_lazy('leads:index')


def user_lead(request):
    u_lead_list = Lead.objects.all()
    lst = []
    for lead in u_lead_list:
        if lead.user.username == request.user.username:
            lst.append(lead)
    context = {'lead_list':lst}
    return render(request, 'leads/mylead.html', context)

leads/templates/leads/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static './leads/style.css' %}">
    <title>&#128523; CRM Project</title>
</head>

<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">CRM</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'leads:index' %}">Home</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'leads:mylead' %}">My Lead</a></li>
                    <li><a href="{% url 'leads:create' %}">Create Lead</a></li>
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li><img src="{{ user.profile.image.url }}" alt="" class="img-circle mt-4 mr-4s" style="width: 30px; height: 30px;"></li>
                        <li><a href="{% url 'users:profile' %}">Profile</a></li>
                        <li><a href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'login' %}">Login</a></li>
                        <li><a href="{% url 'users:register' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
            <div class="container">
            <div class="alert alert-{{message.tags}}">{{ message }}</div>
            </div>
        {% endfor %}
    {% endif %}
    {% block content %}
    {% endblock %}
</body>

</html>

leads/templates/leads/create.html
{% extends 'leads/base.html' %}

{% block content %}
    <div class="container">
        <form action=""></form>
    </div>
{% endblock content %}

leads/templates/leads/index.html
{% extends 'leads/base.html' %}


{% block content %}
<div class="container">
    <div class="row">
        {% if lead_list %}
        {% for lead in lead_list %}
            <div class="col-lg-4">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                    <div class="d-flex">
                        <img src="{{ lead.user.profile.image.url }}" alt="" class="img-circle" style="width: 30px; height: 30px;">
                        <h3 class=" ml-4 mt-0 mb-0">{{ lead.lead_title }}</h3>
                        <div class="ml-auto">
                        {% comment %} {% if user.is_authenticated %}
                        <a href="/leads/{{lead.id}}/update" class="btn btn-default btn-sm ml-auto ">Update</a>
                        <a href="/leads/{{lead.id}}/delete" class="btn btn-danger btn-sm ml-auto ">Delete</a>
                        {% endif %} {% endcomment %}
                        </div>
                    </div>
                    </div>
                    <div class="panel-body">
                        <h4>{{ lead.lead_text }}</h4>
                        <p class="text-muted">Created by: {{lead.user.username }}</p>
                        {% if lead.updated_at %}
                           <p class="text-muted">{{ lead.updated_at }}</p>
                        {% else %}
                            <p class="text-muted">{{lead.created_at }} </p>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
        {% else %}

    </div>
    <div class="alert alert-dismissible alert-danger">
        Leads are not available!
    </div>
    {% endif %}
            {% comment %} <div class="container">
        <h2>You have been logged out.</h2>
        <div class="border-top pt-3">
            <small class="text-muted">
                <a href="{% url 'login' %}" class="ml-2">Log in again</a>
            </small>
        </div>
        </div> {% endcomment %}
</div>
{% endblock  %}

leads/templates/leads/lead_confirm_delete.html
{% extends 'leads/base.html' %}

{% block content %}
    <div class="container">
        <form action="" method="post">
    {% csrf_token %}
    <h3>Are you sure you want to delete "{{ object }}"?</h3>
    <input class="btn btn-danger" type="submit" value="Confirm" />
    </form>
    </div>
{% endblock content %}

leads/templates/leads/lead_form.html
{% extends 'leads/base.html' %}

{% block content %}
    <div class="container">
        <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-default" type="Submit" value="save">
        </form>
    </div>
{% endblock content %}

leads/templates/leads/mylead.html
{% extends 'leads/base.html' %}


{% block content %}
<div class="container">
    <div class="row">
        {% if lead_list %}
        {% for lead in lead_list %}
            <div class="col-lg-4">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                    <div class="d-flex">
                        <img src="{{ lead.user.profile.image.url }}" alt="" class="img-circle" style="width: 30px; height: 30px;">
                        <h3 class=" ml-4 mt-0 mb-0">{{ lead.lead_title }}</h3>
                        <div class="ml-auto">
                        {% if user.is_authenticated %}
                        <a href="/{{lead.id}}/update" class="btn btn-default btn-sm ml-auto ">Update</a>
                        <a href="/{{lead.id}}/delete" class="btn btn-danger btn-sm ml-auto ">Delete</a>
                        {% endif %}
                        </div>
                    </div>
                    </div>
                    <div class="panel-body">
                        {{ lead.lead_text }}
                        {% if lead.updated_at %}
                           <p>{{ lead.updated_at }}</p><br>
                        {% else %}
                            <p>{{lead.created_at }} </p><br>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
        {% else %}

    </div>
    <div class="alert alert-dismissible alert-danger">
        Leads are not available!
    </div>
    {% endif %}
            {% comment %} <div class="container">
        <h2>You have been logged out.</h2>
        <div class="border-top pt-3">
            <small class="text-muted">
                <a href="{% url 'login' %}" class="ml-2">Log in again</a>
            </small>
        </div>
        </div> {% endcomment %}
</div>
{% endblock  %}